### ISSUE TITLE
Task* methods should start task if not started

### ISSUE THREAD

**Issue by shiftkey** [PProvost/AssertEx#5]
Expected: This test should fail.

```
[TestMethod]
public void TestThatTaskDoesNotThrowWorks()
{
    var t = new Task(() => { throw new Exception("Foo"); });
    AssertEx.TaskDoesNotThrow(() => t);
}
```

Actual: test never completes. Requires additional line to get test to fail:

```
[TestMethod]
public void TestThatTaskDoesNotThrowWorks()
{
    var t = new Task(() => { throw new Exception("Foo"); });
    t.Start();
    AssertEx.TaskDoesNotThrow(() => t);
}
```

**Comment by PProvost** [comment]
Hmmm... not so sure about that. If you wanted it to start, you should call Task.Run instead of newing up one. That's the way it was explained to me by Stephen Toub (architect of TAP stuff). I may ask him what he thinks.

**Comment by shiftkey** [comment]
I'm happy to call PEBKAC on this. 

Alternatively, perhaps a instructive error message to indicate that the received task is in an invalid state?

**Comment by PProvost** [comment]
Also an interesting idea. The thing that's got me thinking is that Task.Run() may actually complete too early for us to catch the exception.

I was wondering about something like this:

```
AssertEx.TaskThrows( () => Task.Run( () => {
   throw new Exception("Foo");
} ) );
```

But I hate nested lambdas.

Hmmm...

**Comment by PProvost** [comment]
As I thought about this some more, I realized we may be looking at this
wrong. I started thinking about how and what I would actually be trying
to test here.

I wonder if the actual usage scenario might be more like this:

```
public Task<string> LongRunningOperation()
{
    return Task<string>.Run( () => {
        throw new Exception("Foo");
    });
}

[TestMethod]
public void TestLongRunningOperation()
{
    AssertEx.TaskThrows( async () => {
        await LongRunningOperation();
    } );
}
```

**Comment by JakeGinnivan** [comment]
@shiftkey yeah, a task should never be not started, not a scenario that needs to be catered for.

[TestMethod]
public void TestLongRunningOperation()
{
    var task = Task.Run(()=>throw new InvalidOperationException());
    AssertEx.TaskThrows(task);
}

@PProvost 
That will work fine, the task will be in a faulted state already, so when the Assert.TaskThrows accesses the .Wait() method or the .Result property the exception will be rethrown. 
Also, why do we need TaskThrows(()=>task). A task represents a async operation. PR incoming for some ideas to clean up syntax :)

**Comment by PProvost** [comment]
@shiftkey I talked to Stephen Toub today and he suggested this implementation. What do you think?

```
public static void Throws<T>(Func<Task> func)
{
Assert.Throws<T>(() => func().GetAwaiter().GetResult());
} 
```

**Comment by shiftkey** [comment]
Interesting. I like.

From an API perspective should we drop the Task prefix for those methods and just have overloads on Throws and DoesNotThrow which take in a Task or a Func<Task>?

**Comment by shiftkey** [comment]
Closing this as I think we've clarified the initial question
